### ISSUE TITLE
ntfs mount error

### ISSUE THREAD

**Issue by ifForeverlove** [omnirom/android_external_ntfs-3g#1]
after using on windows,I tried to mount it on an Android device,it took a long time to mount ok.
I got the folllowing logs.
03-31 09:06:18.365 2017 2167 I mount.ntfs: The disk contains an unclean file system (0, 0).
03-31 09:06:18.365 2017 2167 I mount.ntfs: The file system wasn't safely closed on Windows. Fixing.

I wonder if there is a method to solve this question?

**Comment by darkobas** [comment]
Double-click on the Remove Hardware icon located in the System Tray. A window containing a list of the USB devices will appear. Left-click on the Safely Remove Mass Storage Device line that matches your flash drive (for example, Safely Remove Mass Storage Device – Drive(G:)).

**Comment by ifForeverlove** [comment]
yeah,I knew the reason why it happened.What i'd like to say is if the error happened,what I should do to solve the question and let the device mount ok as soon as possible.I wonder if modify ntfs-3g code works and if it works,how to modify?
