### ISSUE TITLE
mount question

### ISSUE THREAD

**Issue by ifForeverlove** [omnirom/android_external_ntfs-3g#2]
Double-click on the Remove Hardware icon located in the System Tray. A window containing a list of the USB devices will appear. Left-click on the Safely Remove Mass Storage Device line that matches your flash drive (for example, Safely Remove Mass Storage Device – Drive(G:)).

_Originally posted by @darkobas in https://github.com/omnirom/android_external_ntfs-3g/issues/1#issuecomment-608246283_

yeah,I knew the reason why it happened.What i'd like to say is if the error happened,what I should do to solve the question and let the device mount ok as soon as possible.I wonder if modify ntfs-3g code works and if it works,how to modify?

**Comment by darkobas** [comment]
Vold should fsck the volume and mount when done.
